### ISSUE TITLE
ImportError: cannot import name 'Filters' from 'telegram.ext'

### ISSUE THREAD

**Issue by jesterhodl** [Einundzwanzig-Podcast/einundzwanzigbot#51]
Hi, I'm trying to launch the bot from docker image.
After cloning the repo, and putting in the token from Bot Father and doing docker-compose up it ultimately ends up with:
```
einundzwanzigbot_1  | Traceback (most recent call last):
einundzwanzigbot_1  |   File "src/main.py", line 2, in <module>
einundzwanzigbot_1  |     from bot import run
einundzwanzigbot_1  |   File "/app/src/bot.py", line 3, in <module>
einundzwanzigbot_1  |     from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, ConversationHandler, CallbackQueryHandler
einundzwanzigbot_1  | ImportError: cannot import name 'Filters' from 'telegram.ext' (/usr/local/lib/python3.8/site-packages/telegram/ext/__init__.py)
twentyoneworldbot_einundzwanzigbot_1 exited with code 1
```

Any ideas?

**Comment by PatrickZGW** [comment]
This is because the python-telegram-bot library was updated to a new version. I pinned the version in the file.
